/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.filteradium.app;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int colorAccent=0x7f040002;
        public static final int colorBackground=0x7f040003;
        public static final int colorGreen=0x7f040007;
        public static final int colorPrimary=0x7f040000;
        public static final int colorPrimaryDark=0x7f040001;
        public static final int colorRed=0x7f040008;
        public static final int colorSurface=0x7f040004;
        public static final int colorTextPrimary=0x7f040005;
        public static final int colorTextSecondary=0x7f040006;
    }
    public static final class id {
        public static final int progressBar=0x7f070000;
        public static final int webView=0x7f070001;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f020000;
        public static final int ic_launcher_round=0x7f020001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int error_connection=0x7f050002;
        public static final int loading=0x7f050001;
        public static final int retry=0x7f050003;
    }
    public static final class style {
        public static final int Theme_Filteradium=0x7f060000;
    }
}
